In [2]:
pandas는 데이타 분석(Data Analysis)을 위해 널리 사용되는 파이썬 라이브러리 패키지이다. 
pandas는 과학용 파이썬 배포판인 아나콘다(Anaconda)에 기본적으로 제공되지만,
아나콘다를 사용하지 않을 경우에는 pip install pandas 를 통해 설치할 수 있다.
이 아티클에서는 pandas의 기본적인 개념과 기초적인 샘플들을 소개한다

SyntaxError: invalid syntax (<ipython-input-2-b53eceb6e8f3>, line 1)

In [4]:
# Series  가장 간단한 1차원 자료구존인 Series는 
import pandas as pd

data = [1,3,5,7,9]
s= pd.Series(data)

In [5]:
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [7]:
# DataFrame
# 2차원 자료구조 행과 열이 있는 데이터를 받아들인다.

import pandas as pd

data = {
    'year': [2016,2017,2018],
    'GDP rate' : [2.8,3.1,3.0],
    'GDP': ['1.637M','1.73M','1.83M']
}

df = pd.DataFrame(data)
df

year  GDP rate     GDP
0  2016       2.8  1.637M
1  2017       3.1   1.73M
2  2018       3.0   1.83M

In [17]:
#Panel
# 3차원 자료구조 Axis 0 , Axis 1, Axis 2 3개의 축

import pandas as pd
import numpy as np
data = np.random.rand(2,3,4)
#print(data)
pd = pd.Panel(data)
print(pd)

#[[[1,3,4,2],[3,4,1,2],[3,5,7,2]],[[1,3,4,2],[3,4,1,2],[3,5,7,2]]]

[[[0.48535224 0.93656553 0.44513544 0.80481648]
  [0.85882411 0.70517153 0.14748093 0.61079019]
  [0.04087585 0.10511941 0.52740554 0.03931541]]

 [[0.2697886  0.57845189 0.39843203 0.99625532]
  [0.43224559 0.22082367 0.28990569 0.46133439]
  [0.14519111 0.8660671  0.23563422 0.14852152]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 3 (major_axis) x 4 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 2
Minor_axis axis: 0 to 3


In [20]:
#데이터 엑세스 
#df["year"] # 이것도 가능
df.year
df[df['year']>2016] # 이런것도 가능
df.head() # 데이터 량이 많은 경우에는 처음 5개 row를 표시해준다.
df.tail() #마지막 5개의 row를 표시해준다.

year  GDP rate    GDP
1  2017       3.1  1.73M
2  2018       3.0  1.83M

In [21]:
sum = df['GDP rate'].sum()# 더하기
avg = df['GDP rate'].mean() # 평균
print(sum,avg)

8.9 2.966666666666667


In [22]:
df.describe()

year  GDP rate
count     3.0  3.000000
mean   2017.0  2.966667
std       1.0  0.152753
min    2016.0  2.800000
25%    2016.5  2.900000
50%    2017.0  3.000000
75%    2017.5  3.050000
max    2018.0  3.100000

In [47]:
# 외부데이터 읽고 쓰기
"""
pandas는 CSV파일, 텍스트 파일,SQL데이터 베이스 ,HDF5포맷등 다양한 외부 데이터 
읽고 쓰는 기능이 있다.
"""
import pandas as pd

test = pd.read_excel('hi.xlsx'⁩, sheet_name =Sheet1)
test

SyntaxError: invalid character in identifier (<ipython-input-47-5853744c2858>, line 8)

In [36]:
import os
print (os.getcwd()) #현재 디렉토리의
print (os.path.realpath('hi.xlsx'))#파일
print (os.path.dirname(os.path.realpath('hi.xlsx')) )#파일이 위치한 디렉토리

/Users/gimjinsu
/Users/gimjinsu/hi.xlsx
/Users/gimjinsu
