In [8]:
import random
import numpy as np

def predict(w, x_i):
    answer = np.tensordot(w, x_i, axes =1)
    
    if answer > 0:
        answer = +1
    elif answer < 0:
        answer = -1
    return answer

def learn(w, x, y):
    is_error_there = True
    while is_error_there:
        is_error_there = False
        for x_i,y_i in zip(x,y):
            answer = predict(w, x_i)
            if answer != y_i:
                w = np.add(w, x_i * y_i)
                is_error_there = True
    return w

x = np.array([[1, 1], [1, 3], [2, 1], [3, 2], [5, 3], [6, 3], [6, 5], [7, 2]])
b = np.ones((x.shape[0],1), dtype = "int")# bias dimension
x = np.concatenate([b,x],axis =1) # x에 bias를 추가해준다.
y = np.array([-1,-1,-1,-1,1,1,1,1]) # y는 결과 값 
y = y.reshape((x.shape[0],1))
w = np.random.random(x.shape[1])
# y = [-1, -1, -1, -1, 1, 1, 1, 1]
# w = [ ]
# for i in range(0, len(x[0])+1):
#     w_i = random.uniform(0, 1)
#     w.append(w_i)

w = learn(w, x, y)
    
# for i in range(0, len(x)):
#     x_i = x[i]
#     y_i = y[i]
#     answer = predict(w, x_i)
#     print(x_i, end=", ")
#     print(y_i, end=", ")
#     print(answer)

for x_i,y_i in zip(x,y):
    answer = predict(w, x_i)
    
    print(x_i, end=", ")
    print(y_i, end=", ")
    print(answer)

[1 1 1], [-1], -1
[1 1 3], [-1], -1
[1 2 1], [-1], -1
[1 3 2], [-1], -1
[1 5 3], [1], 1
[1 6 3], [1], 1
[1 6 5], [1], 1
[1 7 2], [1], 1
