In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier

digits = datasets.load_digits()

x = digits.images.reshape((digits.images.shape[0], digits.images.shape[1]*digits.images.shape[2]))
y = digits.target

x_train = x[:1000]
print(x_train)
y_train = y[:1000]
print(y_train)
x_test = x[1000:]
y_test = y[1000:]

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  3. ...  9.  0.  0.]
 [ 0.  0.  0. ...  6.  0.  0.]
 [ 0.  0.  9. ... 10.  0.  0.]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0
 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9
 5 2 8 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4
 4 7 2 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 8 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7
 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2
 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8 2 0 0 1 7 6 3 2 1 7 3 1 3 9 1
 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2 8 2 2 5 5 4 8 8 4 9 0 8 9 8 0 1 2
 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9
 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8
 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2
 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 3 0 1 2 3 4 5 6 7 8 9 0 1 2

In [2]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(15,), 
                    activation='logistic', 
                    solver='sgd', 
                    tol=1e-4, 
                    learning_rate_init=.1, 
                    verbose=False)

mlp.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15,), learning_rate='constant',
       learning_rate_init=0.1, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [3]:
predictions = mlp.predict(x_test)

In [4]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[75,  0,  0,  0,  0,  1,  0,  0,  2,  1],
       [ 0, 70,  0,  0,  0,  0,  0,  0,  3,  7],
       [ 1,  0, 70,  5,  0,  0,  0,  1,  0,  0],
       [ 0,  1,  4, 62,  0,  6,  0,  0,  3,  3],
       [ 0,  2,  0,  0, 77,  0,  2,  1,  0,  1],
       [ 0,  0,  0,  0,  0, 80,  1,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 80,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  2,  0, 72,  0,  3],
       [ 0,  5,  0,  0,  0,  6,  1,  0, 61,  3],
       [ 0,  0,  0,  0,  0,  5,  0,  3,  1, 72]], dtype=int64)

In [5]:
import pandas as pd

pd.crosstab(y_test, predictions, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted   0   1   2   3   4    5   6   7   8   9  All
True                                                   
0          75   0   0   0   0    1   0   0   2   1   79
1           0  70   0   0   0    0   0   0   3   7   80
2           1   0  70   5   0    0   0   1   0   0   77
3           0   1   4  62   0    6   0   0   3   3   79
4           0   2   0   0  77    0   2   1   0   1   83
5           0   0   0   0   0   80   1   0   0   1   82
6           0   0   0   0   0    0  80   0   0   0   80
7           0   0   0   0   3    2   0  72   0   3   80
8           0   5   0   0   0    6   1   0  61   3   76
9           0   0   0   0   0    5   0   3   1  72   81
All        76  78  74  67  80  100  84  77  70  91  797

In [12]:
print(mlp.coefs_[0])# coefs = 계수


[[ 1.99476867e-02 -1.03208666e-01 -9.51315606e-02  1.71689464e-02
  -1.54285405e-01 -1.57993027e-01  8.68964075e-02 -5.99356563e-02
  -1.64490940e-02  6.30730001e-02 -1.36787272e-02  1.22559547e-01
  -8.67374197e-02  1.28224937e-01  1.50942614e-01]
 [ 2.99630490e-01 -1.12947401e-01  1.55338926e-01  3.44513571e-02
  -2.15451336e-01 -6.28741444e-02  1.41676806e-01 -1.99977404e-01
   1.18484189e-01  1.48088313e-01 -2.08625012e-01  6.64181815e-02
   7.75949123e-02  1.21662342e-01  3.66249168e-02]
 [ 7.10890770e-03  9.25683400e-02 -2.68802709e-01 -3.04960338e-01
   9.48365435e-02 -3.02414126e-02 -1.21914970e-01 -2.50000935e-01
   1.80667931e-02  4.60527141e-01 -1.91686748e-01  4.59111898e-02
  -1.70770682e-01 -5.55559374e-02 -1.19425327e-01]
 [-7.17541168e-02  9.74031816e-03  2.55258403e-01 -7.82249115e-02
   5.61830070e-01 -2.87877704e-02  1.02876109e-01 -5.42546991e-01
  -4.05947945e-02 -9.82233520e-02  9.25152648e-02 -8.80070714e-02
   1.33641333e-01 -8.29497578e-02  1.52270619e-02]
 [ 4

In [13]:
print(mlp.intercepts_[0]) # 0번째 intercepts(절편)
print(mlp.intercepts_[1]) # 1번째 intercepts(절편)

[ 0.18138443 -0.08877135 -0.04765546 -0.0286872  -0.06484458  0.17982154
  0.14837467 -0.07645813  0.11290471  0.13095     0.04978942  0.08361995
 -0.02238777  0.01943257  0.13473397]
[-0.47705719  0.19551326 -0.14183869 -0.73433137 -0.1470048  -0.00986394
  0.04061284  0.04972377  0.79666823  0.3741306 ]


In [19]:
import pandas as pd
import numpy as np
data = pd.read_csv('digits.csv', header = None)
data

#reshape 공부

x_train = np.array(data.iloc[0:1000,0:64])
y_train = np.array(data.iloc[0:1000,64:65]).reshape(1000)
x_test = np.array(data.iloc[1000:1797,0:64])
y_test = np.array(data.iloc[1000:1797,64:65]).reshape(797)


In [3]:
import pandas as pd
s_data = pd.read_csv('simpsons.csv') # csv에서 읽는다.
s_data['gender'] = s_data['gender'].map({'M':0,'F':1}) # gender에서 M은 0 F 1로 바꿔준다.
#print(s_data)

s_data = s_data.drop('Unnamed: 0', axis = 1) #이름을 떨궈낸다. axix 1 ?
x = s_data.drop('gender', axis = 1) # x는 drop을 떨궈낸 나머지 데이터
y = s_data['gender'] # y는 gender(결과값) 데이

print(x)
print(y)

   hair_length  weight  age
0            0     250   36
1           10     150   34
2            2      90   10
3            6      78    8
4            4      20    1
5            1     170   70
6            8     160   41
7           10     180   38
8            6     200   45
0    0
1    1
2    0
3    1
4    1
5    0
6    1
7    0
8    0
Name: gender, dtype: int64


In [30]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3) # 최대 깊이 3이다.

dtc.fit(x,y) #x,y를받아 fit 함수 분류기를 만들어 준다.

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [32]:
from sklearn.tree import export_graphviz
export_graphviz(dtc, out_file = 'decision_tree.dot', #file 의 이름 
                feature_names = x.columns, # 특질 이름 ?? 
               class_names = ['M',"F"], 
               rounded = True)
# decision_tree.dot 파일이 생성된다.

In [33]:
from sklearn import datasets

iris = datasets.load_iris()
print(dir(iris))
print(iris.feature_names)
print(iris.target_names)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [35]:
import pandas as pd

data =pd.DataFrame({
    'sepal length':iris.data[:,0],
    'sepal width':iris.data[:,1],
    'petal length':iris.data[:,2],
    'petal width':iris.data[:,3],
    'species':iris.target
})
data.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [37]:
from sklearn.model_selection import train_test_split

X = data[['sepal length','sepal width', 'petal length','petal length','petal width']]
y = data['species']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3,random_state = 0)

In [38]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators = 100)
clf.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [39]:
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)

In [42]:
from sklearn import svm
#svm 사용 해봄
clf = svm.SVC(gamma = 'auto', kernel = 'rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)