In [2]:
# 2019. 08.19 numpy 4
"""
Array 인덱싱
"""

'\nArray 인덱싱\n'

In [6]:
import numpy as np
arr1 = np.arange(10)
arr1
arr1[0]
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [8]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr2[0,0]

1

In [11]:
arr2[2,3]

12

In [12]:
arr2[:,3]

array([ 4,  8, 12])