In [1]:
#2019.08.20 numpy 5
"""
Array boolean 인덱싱(마스크)
- 마스크 처럼 우리가 가리고 싶은 부분은 가리고 원하는 요소만
  꺼낼 수 있다.
"""

'\nArray boolean 인덱싱(마스크)\n- 마스크 처럼 우리가 가리고 싶은 부분은 가리고 원하는 요소만\n  꺼낼 수 있다.\n'

In [4]:
import numpy as np
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [6]:
# random한수 사용 기대값이 0이다 표준편차가 1인 가우시안 정규 분포
data = np.random.randn(8,4)
data


array([[ 1.97476954,  0.01474662, -2.0286695 ,  0.53577018],
       [ 0.27785083,  0.53776175,  0.02538565, -0.5574458 ],
       [ 1.40260254, -0.52823891, -0.35677709, -1.12110786],
       [ 0.70442802, -0.51023603,  0.35316765, -0.35713105],
       [ 0.37635521, -1.63465755,  0.55019411,  0.63935227],
       [-0.32331132, -0.21585256, -0.69276579,  1.56599769],
       [ 1.30828549,  2.22203802,  0.36134677,  0.21718305],
       [ 0.95777665,  0.35775226, -0.47874909, -0.58393314]])

In [11]:
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask 

array([ True,  True, False, False, False,  True, False,  True])

In [12]:
#위에 범우에 True가 1이 되고 False가 0이된다.
#그러므로 data의 0,1,5,7행을 꺼내온다
data[names_Beomwoo_mask, :]

array([[ 1.97476954,  0.01474662, -2.0286695 ,  0.53577018],
       [ 0.27785083,  0.53776175,  0.02538565, -0.5574458 ],
       [-0.32331132, -0.21585256, -0.69276579,  1.56599769],
       [ 0.95777665,  0.35775226, -0.47874909, -0.58393314]])

In [14]:
#이런식으로 조건식도 가능하다
data[(names == "Kim") | (names == 'Park'), : ]

array([[ 1.40260254, -0.52823891, -0.35677709, -1.12110786],
       [ 1.30828549,  2.22203802,  0.36134677,  0.21718305]])

In [15]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]< 0,2:4]

array([[-0.69276579,  1.56599769]])