In [1]:
# 2019.08.21 Numpy함수
"""
numpy에서 array에 적용되는 함수

"""

'\nnumpy에서 array에 적용되는 함수\n\n'

In [2]:
import numpy as np

arr1 = np.random.randn(5,3)
arr1

array([[-0.89852153,  1.82705613, -1.63705927],
       [-0.20093414,  0.72400403,  0.86660557],
       [ 1.50995425,  0.07737845, -0.70793847],
       [ 1.27681505, -0.96864178,  0.79014157],
       [-1.10214485, -0.61598407,  0.48741271]])

In [3]:
# abs(절대값) 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.89852153, 1.82705613, 1.63705927],
       [0.20093414, 0.72400403, 0.86660557],
       [1.50995425, 0.07737845, 0.70793847],
       [1.27681505, 0.96864178, 0.79014157],
       [1.10214485, 0.61598407, 0.48741271]])

In [5]:
# 각 성분의 제곱근 계산하기( == array ** 0.5)
np.sqrt(arr1)

C:\Users\TEMP.LAPTOP-O3QKMG8C.000\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan, 1.3516864 ,        nan],
       [       nan, 0.85088426, 0.93091652],
       [1.22880196, 0.27816982,        nan],
       [1.12996241,        nan, 0.88889908],
       [       nan,        nan, 0.69814949]])

In [6]:
# 각 성분의 제곱 계산하기(제곱 2 )
np.square(arr1)

array([[0.80734095, 3.3381341 , 2.67996304],
       [0.04037453, 0.52418184, 0.75100522],
       [2.27996185, 0.00598742, 0.50117688],
       [1.63025667, 0.93826689, 0.6243237 ],
       [1.21472327, 0.37943637, 0.23757115]])

In [14]:
# 각 성분을 무리수  e의 지수로 삼은 값을 계산하기
print("무리수 e의 지수로 삼은 값 계산 >>")
print(np.exp(arr1))
print("ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ")
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산
print("자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산 >>")
np_log = np.log(arr1)
print(np_log)
np.nan_to_num(np_log,copy=False) #None 값을 0으로 바꿔준다

무리수 e의 지수로 삼은 값 계산 >>
[[0.4071712  6.21556189 0.19455133]
 [0.8179663  2.06267571 2.37882239]
 [4.52652372 1.0804509  0.49265878]
 [3.58520283 0.37959827 2.20370839]
 [0.33215789 0.54010913 1.6280984 ]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산 >>
[[        nan  0.602706           nan]
 [        nan -0.32295832 -0.14317134]
 [ 0.41207935 -2.55904696         nan]
 [ 0.24436873         nan -0.23554315]
 [        nan         nan -0.71864407]]
[[ 0.          0.602706    0.        ]
 [ 0.         -0.32295832 -0.14317134]
 [ 0.41207935 -2.55904696  0.        ]
 [ 0.24436873  0.         -0.23554315]
 [ 0.          0.         -0.71864407]]
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ


C:\Users\TEMP.LAPTOP-O3QKMG8C.000\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in log
  import sys


In [16]:
print(np.log2(arr1))# log2
print(np.log10(arr1))#Log10

[[        nan  0.86952096         nan]
 [        nan -0.46593037 -0.20655258]
 [ 0.59450484 -3.69192436         nan]
 [ 0.35254956         nan -0.33981693]
 [        nan         nan -1.03678423]]
[[        nan  0.26175189         nan]
 [        nan -0.14025902 -0.06217852]
 [ 0.17896379 -1.11137997         nan]
 [ 0.10612799         nan -0.10229509]
 [        nan         nan -0.31210315]]


C:\Users\TEMP.LAPTOP-O3QKMG8C.000\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.
C:\Users\TEMP.LAPTOP-O3QKMG8C.000\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log10
  


In [23]:
#각 성분의 부호 계산 (+인경우 1 -1인 경우 -1 0인경우 0)
# 퍼셉트론의 sign기호 사용
print(np.sign(arr1))
print("\n","ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ","\n")
#각 성분의 소수 첫번째 자리에서 올림한 값을 계산
print(np.ceil(arr1))


[[-1.  1. -1.]
 [-1.  1.  1.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [-1. -1.  1.]]

 ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ 

[[-0.  2. -1.]
 [-0.  1.  1.]
 [ 2.  1. -0.]
 [ 2. -0.  1.]
 [-1. -0.  1.]]


In [28]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산
print(np.floor(arr1))
print("\nㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ\n")
#각 성분이 Nan인 경우 True를 , 아닌 경우 False를 반환하기
print(np.isnan(arr1))
print("\nㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ\n")
#각 성분이 무한대인 경우 True, 아닌 경우 False 반환
print(np.isinf(arr1))

[[-1.  1. -2.]
 [-1.  0.  0.]
 [ 1.  0. -1.]
 [ 1. -1.  0.]
 [-2. -1.  0.]]

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [29]:
#각 성분에 대해 삼각함수 값을 계산(cos,cosh,sin,sinh,tan)
print(np.cos(arr1))
print("\nㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ\n")
#tanh
print(np.tanh(arr1))


[[ 0.62276741 -0.25346427 -0.06621446]
 [ 0.97988056  0.74915951  0.64741729]
 [ 0.06080454  0.99700778  0.75970404]
 [ 0.28976498  0.56641939  0.70374474]
 [ 0.45168357  0.81620529  0.88354755]]

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

[[-0.71557722  0.94953727 -0.92706035]
 [-0.19827291  0.61938337  0.6996454 ]
 [ 0.90693093  0.07722439 -0.60938247]
 [ 0.85563402 -0.74810682  0.65848923]
 [-0.80126813 -0.54832572  0.45216052]]
