In [1]:
# 2019.08.19 numpy3
"""
- Array 연산

"""

'\n- Array 연산\n\n'

In [5]:
import numpy as np
arr1= np.array([[1,2,3],[4,5,6]])
arr1
arr1.shape

(2, 3)

In [6]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [8]:
# array 덧셈
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [10]:
# array 뺄셈
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [13]:
# array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [15]:
# array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [16]:
"""
추가 정보 
array는 같은 크기를 가져야 서로 연산이 가능함
but numpy에서는 브로드캐스트라는 기능을 제공
? 브로드캐스트란? 서로 크기가 다른 array가 연산이 가능한 것.
"""

'\n추가 정보 \narray는 같은 크기를 가져야 서로 연산이 가능함\nbut numpy에서는 브로드캐스트라는 기능을 제공\n? 브로드캐스트란? 서로 크기가 다른 array가 연산이 가능한 것.\n'

In [18]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [20]:
arr1 + arr3
# [1,2,3],[4,5,6] 이랑 10 ,11,12랑 다 더해줌 

array([[11, 13, 15],
       [14, 16, 18]])

In [21]:
# 스칼라 연산도 가능하다
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
# 요소에 대해 제곱처리
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)